os: linux
dist: xenial
cache: pip
language: python
python:
  - "3.7"


before_install:
  - sudo apt-get update
  - sudo apt-get -y install pandoc  
install:
  - pip install --upgrade pip setuptools wheel
  - |
    for req in ci-requirements.txt dev-requirements.txt opt-requirements.txt requirements.txt; do
      pip install -q -r $req
    done  
before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - sphinx-build --version
  - pandoc --version

env:
  - GEOMSTATS_BACKEND=numpy
  - GEOMSTATS_BACKEND=pytorch
  - GEOMSTATS_BACKEND=tensorflow

deploy:
  - provider: pypi
    username: $PYPI_USER
    password: $PYPI_PASSWORD
    on:
      repo: geomstats/geomstats
      tags: true
    distributions: "sdist bdist_wheel"
    skip_existing: true
